name: hokatsu_score
description: 沖縄県南部の認可保育園入園選考に使われる保育指数（点数）を計算できるアプリ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  google_mobile_ads: ^8.0.0
  flutter_secure_storage: ^10.0.0
  share_plus: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
